name: Caller_Workflow
on:
  workflow_dispatch:

jobs:
  call-code-scanning:
    permissions:
      actions: read
      contents: read
      security-events: write
    uses:  GitActions-POC/Code-Scanning-Repo/.github/workflows/Codacy-security-scan.yml@main
    with:
      output: results.sarif
      format: sarif
      code-quality-check: yes    
  call-common-template:
    needs: call-code-scanning
    if: |
      always() &&
      (needs.call-code-scanning.result == 'skipped' || needs.call-code-scanning.result == 'success')
    permissions: 
      contents: read
      issues: read
      checks: write
      pull-requests: write
    uses:  GitActions-POC/Code-Scanning-Repo/.github/workflows/common_template_java.yml@main
    with:
      GLOBAL_MY_MAPPED_ENV_VAR: staticvar
      junit_files: "**/surefire-reports/TEST-*.xml"
      package: pom.xml
    secrets:
      ADOVARIABLE: "${{ secrets.ADOVARIABLE }}"
      CLIENT_ID: "${{ secrets.CLIENT_ID }}"
      CLIENT_SECRET: "${{ secrets.CLIENT_SECRET }}"
      SUBSCRIPTION_ID: "${{ secrets.SUBSCRIPTION_ID }}"
      TENANT_ID: "${{ secrets.TENANT_ID }}"
