name: Caller_Workflow
on:
  workflow_dispatch:

jobs:
  call-common-template:
    permissions: 
      contents: read
      issues: read
      checks: write
      pull-requests: write
      actions: read
      security-events: write
    uses:  GitActions-POC/Code-Scanning-Repo/.github/workflows/common-template-java-new.yml@main
    with:
      GLOBAL_MY_MAPPED_ENV_VAR: staticvar
      junit_files: "**/surefire-reports/TEST-*.xml"
      package: pom.xml
      output: results.sarif
      format: sarif
      code-quality-check: yes
    secrets:
      ADOVARIABLE: "${{ secrets.ADOVARIABLE }}"
      CLIENT_ID: "${{ secrets.CLIENT_ID }}"
      CLIENT_SECRET: "${{ secrets.CLIENT_SECRET }}"
      SUBSCRIPTION_ID: "${{ secrets.SUBSCRIPTION_ID }}"
      TENANT_ID: "${{ secrets.TENANT_ID }}"
